name: "Terraform Actions"

permissions:
  id-token: write
  contents: read

on:
  push:

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: "ap-northeast-1"

jobs:
  terraform_plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/project
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "ap-northeast-1" # リージョンを指定
          role-to-assume: "arn:aws:iam::013362457766:role/cost-manager-github-action-role" # 作成した IAM ロールの ARN
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
