name: terraform-apply

permissions:
  id-token: write
  contents: read
  pull-requests: write
  statuses: write

on:
  workflow_dispatch:
    inputs:
      refresh_only:
        description: "run state refresh only (not apply)"
        required: true
        default: false
        type: boolean

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: "ap-northeast-1"

  # Terraform
  TF_VERSION: "1.4.4"
  TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  TF_VAR_aws_region: "ap-northeast-1"

jobs:
  terraform_plan:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/project
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: "arn:aws:iam::013362457766:role/cost-manager-github-action-role"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4

      - name: Check format
        run: terraform fmt -check -recursive

      - name: Init
        run: terraform init -upgrade

      - name: Check validate
        run: terraform validate

      - name: Plan
        run: terraform plan -input=false

      - name: Apply
        run: terraform apply -auto-approve
